/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
  {
    _id: "8dbda250-7506-4816-9ef5-49dc3f07a3ff",
    title: "PRODOT 5 in 1 combo Combo Set  (Black, White)",
    seller: "Rj18Wale",
    price: "1,299",
    offerPrice: "995",
    discount: "23% off",
    category: "computerAccessories",
    image: "https://bit.ly/3pzYZnK",
    rating: "3.9",
    features: {
      in_Box: "keyboard, mouse, usb hub, v8 otg, mousepad",
      model: "5 in 1 combo",
      designedFor: "laptop, computer, pc, Tablets, smart tv",
      requirements: "Windows, Linux, Andriod",
      warranty: "1 Year",
    },
  },
  {
    _id: "bfd51862-a05d-4a53-9e0e-3d99c34ceb8a",
    title: "ZEBRONICS 100HB High Speed ZEB-100HB USB Hub  (Black)",
    seller: "indiaflashmartstore",
    price: "420",
    offerPrice: "337",
    discount: "19% off",
    category: "computerAccessories",
    image: "https://bit.ly/3OdoMMI",
    rating: "4.1",
    features: {
      in_Box: "1 x USB Hub",
      designedFor: "laptop, computer, pc, Tablets, smart tv",
      warranty: "1 Year",
      powerCord: "1.62m",
    },
  },
  {
    _id: "47cb0744-2f19-4464-9788-b7216ca852b3",
    title: "PRODOT 5 in 1 combo Combo Set  (Black, White)",
    seller: "RSOsolutions",
    price: "999",
    offerPrice: "235",
    discount: "76% off",
    category: "computerAccessories",
    image: "https://bit.ly/3Om4KzE",
    rating: "3.9",
    features: {
      in_Box: "1 USB HUB",
      designedFor: "laptop, computer, pc, Tablets, smart tv",
      requirements: "Windows, Linux, Andriod",
      warranty: "1 Year",
    },
  },
  {
    _id: "6759bb28-ded6-4814-80ca-3bb87f4721b5",
    title: "JioFi M2S Wireless Data Card  (Black)",
    seller: "No1AssuredSupplier",
    price: "3,459",
    offerPrice: "2,088",
    discount: "39% off",
    category: "computerAccessories",
    image: "https://bit.ly/42Xaggr",
    rating: "4.2",
    features: {
      in_Box: "1 Datacard, Adapter, Battery, Cable, Warranty Card, User Manual",
      model: "M2S Wireless",
      designedFor: "laptop, computer, pc, Tablets, smart tv",
      requirements: "Windows, Linux, Andriod",
      warranty: "1 Year",
      color: "Black",
      networkType: "LTE 2300/1800/850 MHz, WLAN: IEEE 802.11b/g/n 2.4 GHz",
    },
  },
  {
    _id: "a4d34b33-ee01-4235-88a0-ecf5ecc4137c",
    title:
      "WACOM DTK-1660 Cintiq 16 13.6 x 7.6 inch Graphics Tablet  (Black, Connectivity - USB)",
    seller: "RetailNet",
    price: "69,775",
    offerPrice: "61,490",
    discount: "11% off",
    category: "computerAccessories",
    image: "https://bit.ly/3ocSFCh",
    rating: "4.0",
    features: {
      in_Box:
        "1 - Tablet, 3-in-1 cable (1.8 m), AC adapter (12 V, 3 A, 36 W), power cable (1.8 m), Quick Start Guide, warranty card",
      model: "DTK-1660",
      designedFor: "laptop, computer, pc, Tablets, smart tv",
      requirements: "Windows, Linux, Andriod",
      warranty: "1 Year",
      connectivity: "USB",
      series: "Wacom Cintiq 16",
      screenSize: "39.6 cm (15.6 in) / Full HD 1920 x 1080",
    },
  },
  {
    _id: "82c764f5-8dd5-4896-9f30-9cc8b067edee",
    title: "ZEBRONICS Zeb-U735 UPS",
    seller: "RetailNet",
    price: "3,399",
    offerPrice: "1,899",
    discount: "44% off",
    category: "computerAccessories",
    image: "https://bit.ly/3M7V7lE",
    rating: "3.9",
    features: {
      in_Box: "1 UPS, User Manual",
      model: "Zeb-U735",
      warranty: "3 Year",
      overloadProtection: "No",
      output: "230 V",
      outputWattage: "360 W",
      displayType: "LED",
      batteryType: "Sealed Lead Acid Battery",
      chargeTime: "6 - 8 hrs to Charge 90% (After Complete Discharge)",
      capacity: "12V/7AH",
    },
  },
  {
    _id: "6b8659e9-9eb3-4085-81be-62220d067e9a",
    title:
      "WACOM DTK-1660 Cintiq 16 13.6 x 7.6 inch Graphics Tablet  (Black, Connectivity - USB)",
    seller: "RetailNet",
    price: "69,775",
    offerPrice: "61,490",
    discount: "11% off",
    category: "computerAccessories",
    image: "https://bit.ly/3ocSFCh",
    rating: "4.0",
    features: {
      in_Box:
        "1 - Tablet, 3-in-1 cable (1.8 m), AC adapter (12 V, 3 A, 36 W), power cable (1.8 m), Quick Start Guide, warranty card",
      model: "DTK-1660",
      designedFor: "laptop, computer, pc, Tablets, smart tv",
      requirements: "Windows, Linux, Andriod",
      warranty: "1 Year",
      connectivity: "USB",
      series: "Wacom Cintiq 16",
      screenSize: "39.6 cm (15.6 in) / Full HD 1920 x 1080",
    },
  },
  {
    _id: "020d4264-f11e-4d2f-b7aa-820b218f47ba",
    title:
      "Bestor Dual-Sided Multifunctional Desk Pad ,Waterproof Desk Blotter Protector,Extended Mouse Pad/Desk Mat for Work from Home/Office/Gaming | Vegan PU Leather | Anti-Skid, Anti-Slip, Reversible Splash-Proof – Deskspread ~ Navy Blue & Yellow Mousepad  (Navy Blue, Golden Yellow)",
    seller: "BEST0R",
    price: "1,499",
    offerPrice: "489",
    discount: "67% off",
    category: "computerAccessories",
    image: "https://bit.ly/42ZAw9P",
    rating: "4.5",
    features: {
      in_Box: "1 Unit of MousePad",
      material: "PU Leatherette",
      suitableFor: "computer, laptop, gaming console",
    },
  },
  {
    _id: "4c28a5e1-7c3a-441b-a923-ef8b45f3a311",
    title: "Airtel AMF-311WW Data Card  (Black)",
    seller: "BrandRootAT",
    price: "3,249",
    offerPrice: "2,930",
    discount: "9% off",
    category: "computerAccessories",
    image: "https://bit.ly/42FVb36",
    rating: "3.9",
    features: {
      in_Box: "1 Datacard, 1 Battery, 1 Charging Cable, 1 User Manual",
      model: "AMF-311WW",
      designedFor: "laptop, computer, pc, Tablets, smart tv",
      requirements: "Windows, Linux, Andriod",
      warranty: "1 Year",
      color: "Black",
      network:
        "4G LTE,supports Wi-Fi 2.4GHz, Powerful Battery (2300 mAh), Enjoy 4G speeds even on non-4G devices",
    },
  },
  {
    _id: "46e886b6-54f6-46e1-a281-0b63ed02b553",
    title:
      "amd Ryzen 3 3200G with Radeon Vega 8 Graphics (YD3200C5FHBOX) 3.6 Ghz Upto 4 GHz AM4 Socket 4 Cores 4 Threads 2 MB L2 4 MB L3 Desktop Processor  (Silver)",
    seller: "RetailNet",
    price: "13,000",
    offerPrice: "7,699",
    discount: "40% off",
    category: "computerAccessories",
    image: "https://bit.ly/42FwfZw",
    rating: "4.1",
    features: {
      in_Box: "1 AMD Processor",
      series: "Ryzen™ 3 3200G",
      warranty: "3 Years",
      color: "Silver",
      maxTurboSpeed: "4GHz",
      memoryType: "DDR4",
    },
  },
  {
    _id: "5ebe7a5f-3bfa-4962-af3f-2ea6665317f6",
    title:
      "WACOM CTL-4100/K0-CX Intuos Small 3.7 x 0.35 inch Graphics Tablet  (Black, Connectivity - USB)",
    seller: "RetailNet",
    price: "7,399",
    offerPrice: "5,249",
    discount: "29% off",
    category: "computerAccessories",
    image: "https://bit.ly/3o8uq8g",
    rating: "4.3",
    features: {
      in_Box:
        "Wacom Intuos creative pen tablet small, Pressure-sensitive, battery-free Wacom Pen 4K, PVC-free USB cable with cable tidy and L-shaped connector, 3 extra standard nibs (located inside pen), nib removal tool on end of pen, Quick start guide, Regulation sheet",
      model: "CTL-4100/K0-CX",
      designedFor: "laptop, computer, pc, Tablets, smart tv",
      requirements: "Windows, Linux, Andriod",
      warranty: "1 Year",
    },
  },
  {
    _id: "c492d21e-d0dc-4e04-9885-69f287179486",
    title:
      "WACOM CTL-4100/K0-CX Intuos Small 3.7 x 0.35 inch Graphics Tablet  (Black, Connectivity - USB)",
    seller: "RetailNet",
    price: "7,399",
    offerPrice: "5,249",
    discount: "29% off",
    category: "computerAccessories",
    image: "https://bit.ly/3o8uq8g",
    rating: "4.3",
    features: {
      in_Box:
        "Wacom Intuos creative pen tablet small, Pressure-sensitive, battery-free Wacom Pen 4K, PVC-free USB cable with cable tidy and L-shaped connector, 3 extra standard nibs (located inside pen), nib removal tool on end of pen, Quick start guide, Regulation sheet",
      model: "CTL-4100/K0-CX",
      designedFor: "laptop, computer, pc, Tablets, smart tv",
      requirements: "Windows, Linux, Andriod",
      warranty: "1 Year",
    },
  },
  {
    _id: "8a2dc2b5-5f37-4c1f-9e28-dc49d4027863",
    title:
      "KARWAN Back Cover for Poco M4 Pro  (Green, Shock Proof, Silicon, Pack of: 1)",
    seller: "KARWAN",
    price: "999",
    offerPrice: "319",
    discount: "68% off",
    category: "computerAccessories",
    image: "https://bit.ly/42Mrrli",
    rating: "3.8",
    features: {
      in_Box: "1",
      model: "SQUAREPLATING-POCO-M4PRO-GREEN",
      designedFor: "Poco M4 Pro",
      color: "Green",
    },
  },
  {
    _id: "c2b6d61f-97f6-48b1-afd8-b4df0789bd2a",
    title:
      "ShopsyCart SmartBuy Back Cover for Google Pixel 6a  (Transparent, Grip Case, Silicon, Pack of: 1)",
    seller: "GRAB11",
    price: "499",
    offerPrice: "189",
    discount: "62% off",
    category: "computerAccessories",
    image: "https://bit.ly/3pNtFC0",
    rating: "4.1",
    features: {
      in_Box: "1 Mobile Back Cover",
      model: "FKSB-C-GL-PXL-6A-TRA",
      designedFor: "Google Pixel 6a",
      color: "Transparent",
    },
  },
  {
    _id: "396ddb45-129a-4842-b7bf-d1afb8af7faf",
    title:
      "Bestor USB C to HDMI Adapter, 6 in 1 USB C Hub Laptop USB C Adapter 6 in 1 USB C Hub USB Hub  (Grey)",
    seller: "BEST0R",
    price: "2,999",
    offerPrice: "1,299",
    discount: "56% off",
    category: "computerAccessories",
    image: "https://bit.ly/42DVxad",
    rating: "4.3",
    features: {
      in_Box:
        "Multiport Hub with 4K HDMI, 3 USB 3.0 Port, SD/TF Card Reader for MacBook Pro/Air 2020 2019 2018, Chromebook",
      designedFor: "laptop, computer, pc, Tablets, smart tv",
      warranty: "1 Year",
      powerCord: "1.62m",
    },
  },
  {

        _id:"fb5b277e-fb7c-11ed-be56-0242ac120002",
        title:"vivo T2x 5G (Glimmer Black, 128 GB)  (6 GB RAM)",
        seller:"Nameipic",
        price:"18,999",
        offerPrice:"13,999",
        discount:"26% off",
        category:"mobiles",
        image:"https://shorturl.at/dem68",
        rating:"4.5",
        features:
        { 
         "In Box":"Handset, USB Power Adapter, USB Cable, Sim Eject Tool, Phone Case, Protective Film (Applied), Documentation",
         Model:"V2253",
         "Model Name":"T2x 5G",
         Color:"Glimmer Black",
         "SIM Type":"Dual Sim",
         Display:"16.71 cm (6.58 inch)",
         Resolution:"2408 x 1080 Pixels",
         OS:"Android 13",
         Processor:"Dimensity 6020",
         "Processor Core":"Octa Core",
         Storage:"128 GB",
         RAM:"6 GB",
         "Primary Camera":"50MP + 2MP",
         "Secondary Camera":"8MP Front Camera",
         "Netwrork Type":"5G, 4G, 3G",
         "Micro USB Version":"USB (Type C)",
         "Wi-Fi version":"Supports 2.4 GHz and 5 GHz Dual Band",
        }
       },
       {
        _id: "b165ef0e-fba0-11ed-be56-0242ac120002",
        title: "vivo T2 5G (Nitro Blaze, 128 GB)  (6 GB RAM)",
        seller: "Nameipic",
        price: "23,999",
        offerPrice: "18,999",
        discount: "20% off",
        category: "mobiles",
        image: "https://shorturl.at/bfNO8",
        rating: "4.5",
        features:
        {
            "In Box": "Handset, USB Power Adapter, USB Cable, Sim Eject Tool, Phone Case, Protective Film (Applied), Documentation",
            Model: "V2240",
            "Model Name": "T2 5G",
            Color: "Nitro Blaze",
            "SIM Type": "Dual Sim",
            Display: "16.21 cm (6.38 inch)",
            Resolution: "2400 x 1080 Pixels",
            OS: "Android 13",
            Processor: "Snapdragon 695",
            "Processor Core": "Octa Core",
            Storage: "128 GB",
            RAM: "6 GB",
            "Primary Camera": "64 MP (OIS) + 2MP",
            "Secondary Camera": "16MP Front Camera",
            "Netwrork Type": "5G, 4G, 3G",
            "Micro USB Version": "USB (Type C)",
            "Wi-Fi version": "Supports 2.4 GHz and 5 GHz Dual Band",
            Battery: "4500 mAh",
            Warranty: "1 Year of Device & 6 Months for Inbox Accessories"
        }
    },
    {
        _id: "c2a46b82-fba1-11ed-be56-0242ac120002",
        title: "APPLE iPhone 13 (Starlight, 128 GB)",
        seller: "SuperComNet",
        price: "69,900",
        offerPrice: "62,999",
        discount: "9% off",
        category: "mobiles",
        image: "https://shorturl.at/lsT35",
        rating: "4.7",
        features:
        {
            "In Box": "iPhone, USB-C to Lightning Cable, Documentation",
            Model: "MLPG3HN/A",
            "Model Name": "iPhone 13",
            Color: "Starlight",
            "SIM Type": "Dual Sim",
            Display: "15.49 cm (6.1 inch)",
            Resolution: "2532 x 1170 Pixels",
            OS: "iOS 15",
            Processor: "A15 Bionic Chip",
            "Processor Core": "Hexa Core",
            Storage: "128 GB",
            RAM: "4GB RAM",
            "Primary Camera": "12MP + 12MP",
            "Secondary Camera": "12MP Front Camera",
            "Netwrork Type": "5G, 4G, 3G, 2G",
            "Micro USB Version": "USB‑C to Lightning Cable",
            "Wi-Fi version": "Wi-Fi 6 (802.11ax) with 2x2 MIMO",
            Battery: "3227 mAh",
            Warranty: "Brand Warranty for 1 Year"
        }
    },
    {
        _id: "ca64e9a4-fba2-11ed-be56-0242ac120002",
        title: "POCO M4 5G (Power Black, 64 GB)  (4 GB RAM)",
        seller: "CLIENTEROecom",
        price: "15,999",
        offerPrice: "12,999",
        discount: "18% off",
        category: "mobiles",
        image: "https://shorturl.at/jzGXZ",
        rating: "4.2",
        features:
        {
            "In Box": "Handset, 22.5 W Power Adapter, USB Type A-C Cable, Sim Ejector Tool, Transparent Case, Pre-Applied Screen Protector, User Guide, Warranty Card",
            Model: "MZB0BRWIN",
            "Model Name": "M4 5G",
            Color: "Power Black",
            "SIM Type": "Dual Sim",
            Display: "16.71 cm (6.58 inch)",
            Resolution: "2400 x 1080 Pixels",
            OS: "Android 12",
            Processor: "Mediatek Dimensity 700",
            "Processor Core": "Octa Core",
            Storage: "64 GB",
            RAM: "4GB RAM",
            "Primary Camera": "50MP + 2MP",
            "Secondary Camera": "8MP Front Camera",
            "Netwrork Type": "5G, 4G, 3G, 2G",
            "Micro USB Version": "USB (Type C)",
            "Wi-Fi version": "802.11 a/b/g/n/ac (2.4 GHz | 5GHz)",
            Battery: "5000 mAh",
            Warranty: "1 Year Warranty for Handset and 6 Months for Accessories"
        }
    },
    {
        _id: "bae8afd2-fba3-11ed-be56-0242ac120002",
        title: "REDMI Note 12 Pro 5G (Stardust Purple, 128 GB)  (6 GB RAM)",
        seller: "EComyalgarTrade",
        price: "27,999",
        offerPrice: "24,999",
        discount: "10% off",
        category: "mobiles",
        image: "https://shorturl.at/iGW57",
        rating: "4.3",
        features:
        {
            "In Box": "Handset, 67 W Charger, USB Type-C Cable, Sim Eject Tool, Protective Case, Quick Start Guide, Warranty Card",
            Model: "MZB0DD3IN",
            "Model Name": "Note 12 Pro 5G",
            Color: "Stardust Purple",
            "SIM Type": "Dual Sim",
            Display: "16.94 cm (6.67 inch)",
            Resolution: "2400 x 1080 Pixels",
            OS: "Android 12",
            Processor: "Mediatek Dimensity 1080",
            "Processor Core": "Octa Core",
            Storage: "128 GB",
            RAM: "6GB RAM",
            "Primary Camera": "50MP (OIS) + 8MP + 2MP",
            "Secondary Camera": "16MP Front Camera",
            "Netwrork Type": "5G, 4G VOLTE, 4G, 3G, 2G",
            "Micro USB Version": "USB (Type C)",
            "Wi-Fi version": "Wi-Fi 6, Supports 2.4 GHz and 5 GHz Dual Band",
            Battery: "5000 mAh",
            Warranty: "1 Year Manufacturer Warranty for Phone and 6 Months Warranty for In the Box Accessories"
        }
    },
    {
        _id: "5622fc32-fba4-11ed-be56-0242ac120002",
        title: "Infinix HOT 20 5G (Space Blue, 64 GB)  (4 GB RAM)",
        seller: "Flashstar Commerce",
        price: "17,999",
        offerPrice: "11,499",
        discount: "36% off",
        category: "mobiles",
        image: "https://shorturl.at/eikv3",
        rating: "4.2",
        features:
        {
            "In Box": "Handset, Adaptor, USB Type-C Cable, TPU Case, SIM Ejector Pin, Quick Start Guide, Warranty Card, Xclub Card",
            Model: "X666 4+64",
            "Model Name": "HOT 20 5G",
            Color: "Space Blue",
            "SIM Type": "Dual Sim",
            Display: "16.76 cm (6.6 inch)",
            Resolution: "1080 x 2408 Pixels",
            OS: "Android 12",
            Processor: "Dimensity 810",
            "Processor Core": "Octa Core",
            Storage: "64 GB",
            RAM: "4 GB",
            "Primary Camera": "50MP + AI Lens",
            "Secondary Camera": "8MP Front Camera",
            "Netwrork Type": "5G, 4G, 3G, 2G",
            "Micro USB Version": "USB (Type C)",
            "Wi-Fi version": "802.11 a/b/g/n/ac",
            Battery: "5000 mAh",
            Warranty: "1 Year on Handset and 6 Months on Accessories"
        }
    },
    {
        _id: "281478c4-fba5-11ed-be56-0242ac120002",
        title: "vivo T2 5G (Nitro Blaze, 128 GB)  (6 GB RAM)",
        seller: "Nameipic",
        price: "23,999",
        offerPrice: "18,999",
        discount: "20% off",
        category: "mobiles",
        image: "https://shorturl.at/hEHQR",
        rating: "4.5",
        features:
        {
            "In Box": "Handset, USB Power Adapter, USB Cable, Sim Eject Tool, Phone Case, Protective Film (Applied), Documentation",
            Model: "V2240",
            "Model Name": "T2 5G",
            Color: "Nitro Blaze",
            "SIM Type": "Dual Sim",
            Display: "16.21 cm (6.38 inch)",
            Resolution: "2400 x 1080 Pixels",
            OS: "Android 13",
            Processor: "Snapdragon 695",
            "Processor Core": "Octa Core",
            Storage: "128 GB",
            RAM: "6 GB",
            "Primary Camera": "64 MP (OIS) + 2MP",
            "Secondary Camera": "16MP Front Camera",
            "Netwrork Type": "5G, 4G, 3G",
            "Micro USB Version": "USB (Type C)",
            "Wi-Fi version": "Supports 2.4 GHz and 5 GHz Dual Band",
            Battery: "4500 mAh",
            Warranty: "1 Year of Device & 6 Months for Inbox Accessories"
        }
    },
    {
        _id: "daec1f7e-fba5-11ed-be56-0242ac120002",
        title: "vivo V27 5G (Noble Black, 128 GB)  (8 GB RAM)",
        seller: "Nameipic",
        price: "36,999",
        offerPrice: "32,999",
        discount: "10% off",
        category: "mobiles",
        image: "https://shorturl.at/tyEY5",
        rating: "4.4",
        features:
        {
            "In Box": "Handset, Type-C to USB Cable, USB Power Adapter, Eject Tool, Phone Case, Protective Film (Applied), Documentation",
            Model: "V2231|V2246",
            "Model Name": "V27 5G",
            Color: "Noble Black",
            "SIM Type": "Dual Sim",
            Display: "17.22 cm (6.78 Inch)",
            Resolution: "2400 x 1080 Pixels",
            OS: "Android 13",
            Processor: "Mediatek Dimensity 7200 5G",
            "Processor Core": "Octa Core",
            Storage: "128 GB",
            RAM: "8 GB",
            "Primary Camera": "50MP (OIS) + 8MP + 2MP",
            "Secondary Camera": "50MP Front Camera",
            "Netwrork Type": "5G, 4G, 3G, 2G",
            "Micro USB Version": "USB (Type C)",
            "Wi-Fi version": "Supports 2.4 GHz and 5.0 GHz",
            Battery: "4600 mAh",
            Warranty: "1 Year Brand Warranty"
        }
    },
    {
        _id: "643a2f82-fba6-11ed-be56-0242ac120002",
        title: "POCO M4 5G (Power Black, 64 GB)  (4 GB RAM)",
        seller: "CLIENTEROecom",
        price: "15,999",
        offerPrice: "12,999",
        discount: "18% off",
        category: "mobiles",
        image: "https://shorturl.at/lzZ49",
        rating: "4.2",
        features:
        {
            "In Box": "Handset, 22.5 W Power Adapter, USB Type A-C Cable, Sim Ejector Tool, Transparent Case, Pre-Applied Screen Protector, User Guide, Warranty Card",
            Model: "MZB0BRWIN",
            "Model Name": "M4 5G",
            Color: "Power Black",
            "SIM Type": "Dual Sim",
            Display: "16.71 cm (6.58 inch)",
            Resolution: "2400 x 1080 Pixels",
            OS: "Android 12",
            Processor: "Mediatek Dimensity 700",
            "Processor Core": "Octa Core",
            Storage: "64 GB",
            RAM: "4 GB",
            "Primary Camera": "50MP + 2MP",
            "Secondary Camera": "8MP Front Camera",
            "Netwrork Type": "5G, 4G, 3G, 2G",
            "Micro USB Version": "USB (Type C)",
            "Wi-Fi version": "802.11 a/b/g/n/ac (2.4 GHz | 5GHz)",
            Battery: "5000 mAh",
            Warranty: "1 Year Warranty for Handset and 6 Months for Accessories"
        }
    },
    {
        _id: "eee6197a-fba6-11ed-be56-0242ac120002",
        title: "SAMSUNG Galaxy F14 5G (B.A.E. Purple, 128 GB)  (6 GB RAM)",
        seller: "MYTHANGLORYRetail",
        price: "18,490",
        offerPrice: "14,490",
        discount: "21% off",
        category: "mobiles",
        image: "https://shorturl.at/bgHIS",
        rating: "4.2",
        features:
        {
            "In Box": "Handset, Type-C Data Cable, Quick Start Guide, Sim Ejection Pin",
            Model: "SM-E146BLVHINS",
            "Model Name": "Galaxy F14 5G",
            Color: "B.A.E. Purple",
            "SIM Type": "Dual Sim",
            Display: "16.76 cm (6.6 inch)",
            Resolution: "2408 x 1080 Pixels",
            OS: "Android 13",
            Processor: "Exynos 1330, Octa Core",
            "Processor Core": "Octa Core",
            Storage: "128 GB",
            RAM: "6 GB",
            "Primary Camera": "50MP + 2MP",
            "Secondary Camera": "13MP Front Camera",
            "Netwrork Type": "5G, 4G, 3G, 2G",
            "Micro USB Version": "USB (Type C)",
            "Wi-Fi version": "802.11",
            Battery: "6000 mAh",
            Warranty: "1 Year Manufacturer Warranty for Device and 6 Months Manufacturer Warranty for In-Box Accessories"
        }
    },
    {
        _id: "9bfa74d0-fba7-11ed-be56-0242ac120002",
        title: "REDMI Note 12 Pro 5G (Glacier Blue, 128 GB)  (6 GB RAM)",
        seller: "EComyalgarTrade",
        price: "27,999",
        offerPrice: "24,999",
        discount: "10% off",
        category: "mobiles",
        image: "https://shorturl.at/lmtFW",
        rating: "4.3",
        features:
        {
            "In Box": "Handset, 67 W Charger, USB Type-C Cable, Sim Eject Tool, Protective Case, Quick Start Guide, Warranty Card",
            Model: "MZB0CXPIN",
            "Model Name": "Note 12 Pro 5G",
            Color: "Glacier Blue",
            "SIM Type": "Dual Sim",
            Display: "16.94 cm (6.67 inch)",
            Resolution: "2400 x 1080 Pixels",
            OS: "Android 12",
            Processor: "Mediatek Dimensity 1080",
            "Processor Core": "Octa Core",
            Storage: "128 GB",
            RAM: "6 GB",
            "Primary Camera": "50MP (OIS) + 8MP + 2MP",
            "Secondary Camera": "16MP Front Camera",
            "Netwrork Type": "5G, 4G VOLTE, 4G, 3G, 2G",
            "Micro USB Version": "USB (Type C)",
            "Wi-Fi version": "Wi-Fi 6, Supports 2.4 GHz and 5 GHz Dual Band",
            Battery: "5000 mAh",
            Warranty: "1 Year Manufacturer Warranty for Phone and 6 Months Warranty for In the Box Accessories"
        }
    },
    {
        _id: "22c6ff24-fba8-11ed-be56-0242ac120002",
        title: "MOTOROLA g73 5G (Midnight Blue, 128 GB)  (8 GB RAM)",
        seller: "MTAILMODEECOM",
        price: "21,999",
        offerPrice: "16,999",
        discount: "22% off",
        category: "mobiles",
        image: "https://rb.gy/fkil2",
        rating: "3.9",
        features:
        {
            "In Box": "Handset, Charger, USB Cable, Guides, Sim Tool, Protective Cover",
            Model: "PAUX0023IN",
            "Model Name": "g73 5G",
            Color: "Midnight Blue",
            "SIM Type": "Dual Sim",
            Display: "16.51 cm (6.5 inch)",
            Resolution: "2400 x 1080 Pixels",
            OS: "Android 13",
            Processor: "Mediatek Dimensity 930",
            "Processor Core": "Octa Core",
            Storage: "128 GB",
            RAM: "6 GB",
            "Primary Camera": "50MP + 8MP",
            "Secondary Camera": "16MP Front Camera",
            "Netwrork Type": "2G, 3G, 4G, 5G",
            "Micro USB Version": "USB (Type C)",
            "Wi-Fi version": "Wi-Fi 802.11 a/b/g/n/ac (2.4 GHz | 5 GHz)",
            Battery: "5000 mAh",
            Warranty: "1 Year Manufacturer Warranty for Phone and 6 Months Warranty for In the Box Accessories"
        }
    },
    {
        _id: "bdd7ccbe-fba8-11ed-be56-0242ac120002",
        title: "vivo V27 5G (Magic Blue, 128 GB)  (8 GB RAM",
        seller: "MTAILMODEECOM",
        price: "36,999",
        offerPrice: "32,999",
        discount: "10% off",
        category: "mobiles",
        image: "https://rb.gy/vwo87",
        rating: "4.4",
        features:
        {
            "In Box": "Handset, Type-C to USB Cable, USB Power Adapter, Eject Tool, Phone Case, Protective Film (Applied), Documentation",
            Model: "V2231|V2246",
            "Model Name": "V27 5G",
            Color: "Magic Blue",
            "SIM Type": "Dual Sim",
            Display: "17.22 cm (6.78 Inch)",
            Resolution: "2400 x 1080 Pixels",
            OS: "Android 13",
            Processor: "Mediatek Dimensity 7200 5G",
            "Processor Core": "Octa Core",
            Storage: "128 GB",
            RAM: "8 GB",
            "Primary Camera": "50MP (OIS) + 8MP + 2MP",
            "Secondary Camera": "50MP Front Camera",
            "Netwrork Type": "5G, 4G, 3G, 2G",
            "Micro USB Version": "USB (Type C)",
            "Wi-Fi version": "Supports 2.4 GHz and 5.0 GHz",
            Battery: "4600 mAh",
            Warranty: "1 Year Brand Warranty"
        }
    },
    {
        _id: "846d8120-fba9-11ed-be56-0242ac120002",
        title: "APPLE iPhone 14 ((PRODUCT)RED, 128 GB)",
        seller: "BTPLD",
        price: "79,900",
        offerPrice: "69,999",
        discount: "12% off",
        category: "mobiles",
        image: "https://rb.gy/invwa",
        rating: "4.6",
        features:
        {
            "In Box": "Handset, USB-C to Lightning Cable, Documentation",
            Model: "MPVA3HN/A",
            "Model Name": "iPhone 14",
            Color: "(PRODUCT)RED",
            "SIM Type": "Dual Sim",
            Display: "15.49 cm (6.1 inch)",
            Resolution: "2532 x 1170 Pixels",
            OS: "iOS 16",
            Processor: "A15 Bionic Chip, 6 Core Processor",
            "Processor Core": "Hexa Core",
            Storage: "128 GB",
            RAM: "6GB of RAM",
            "Primary Camera": "12MP + 12MP",
            "Secondary Camera": "12MP Front Camera",
            "Netwrork Type": "5G, 4G VOLTE, 4G, 3G, 2G",
            "Micro USB Version": "USB‑C to Lightning Cable",
            "Wi-Fi version": "v5.3",
            Battery: "3200 mAh",
            Warranty: "1 Year Warranty for Phone and 6 Months Warranty for In-Box Accessories"
        }
    },
    {
        _id: "7d1f4a06-fbaa-11ed-be56-0242ac120002",
        title: "POCO M4 Pro 5G (Yellow, 128 GB)  (8 GB RAM)",
        seller: "Truenet Commerce",
        price: "21,999",
        offerPrice: "15,999",
        discount: "27% off",
        category: "mobiles",
        image: "https://rb.gy/s8lm6",
        rating: "4.2",
        features:
        {
            "In Box": "Handset, 33W Power Adapter, USB Type A-C Cable, Sim Ejector Tool, Transparent Case, Pre-Applied Screen Protector, User Guide, Warranty Card",
            Model: "MZB0BH1IN",
            "Model Name": "M4 Pro 5G",
            Color: "Yellow",
            "SIM Type": "Dual Sim",
            Display: "16.76 cm (6.6 inch)",
            Resolution: "2400 x 1080 Pixels",
            OS: "Android 11",
            Processor: "Mediatek Dimensity 810",
            "Processor Core": "Octa Core",
            Storage: "128 GB",
            RAM: "8GB of RAM",
            "Primary Camera": "50MP + 8MP",
            "Secondary Camera": "16MP Front Camera",
            "Netwrork Type": "5G, 4G, 3G, 2G",
            "Micro USB Version": "USB (Type C)",
            "Wi-Fi version": "802.11 a/b/g/n (2.4 GHz | 5 GHz)",
            Battery: "5000 mAh",
            Warranty: "One Year for Handset, 6 Months for Accessories"
        }
    },
    {
        _id: "5065246c-fbab-11ed-be56-0242ac120002",
        title: "ASUS Vivo AiO V222 Pentium Dual Core (8 GB DDR4/256 GB SSD/Windows 11 Home/21.5 Inch Screen/V222FAK-WA152W)  (White, 387 mm x 489 mm x 164 mm, 4.8 kg)",
        seller: "MTAILMODEECOM",
        price: "48,990",
        offerPrice: "32,990",
        discount: "32% off",
        category: "computers",
        image: "https://rb.gy/2i8ps",
        rating: "4.3",
        features:
        {
            "In Box": "All-in-One Desktop, Wireless Keyboard, Wireless Mouse, Power Adapter, User Manual",
            Model: "V222FAK-WA152W",
            "Model Name": "Vivo AiO V222",
            Color: "White",
            Brand:"ASUS",
            Display: "21.5 Inch",
            Resolution: "1920 x 1080 Pixel",
            OS: "Windows 11 Home",
            Processor: "Pentium Dual Core",
            "Processor Model": "Intel Pentium Gold 6405U",
            Storage: "256 GB SSD",
            USB:"1 x USB 2.0 Type-A, 4 x USB 3.2 Gen 1 Type-A",
            Bluetooth:"v5.0",
            HDMI:"1 x HDMI 1.4",
            RAM: "8GB of RAM",
            "Wi-Fi version": "Wi-Fi 5(802.11ac) (Dual band) 1*1",
            Warranty: "1 Year Onsite Warranty ASUS Warranty and Free Transit Insurance"
        }
    },
    {
        _id: "5a86a8b6-fbac-11ed-be56-0242ac120002",
        title: "HP All-in-One Core i3 (8 GB DDR4/1 TB/256 GB SSD/Windows 11 Home/21.5 Inch Screen/22-dd2456)  (Jet black, 380.7 mm x 490 mm x 243 mm, 5.7 kg)",
        seller: "MTAILMODEECOM",
        price: "60,865",
        offerPrice: "51,990",
        discount: "14% off",
        category: "computers",
        image: "https://t.ly/p_JcG",
        rating: "4.6",
        features:
        {
            "In Box": "All-in-One Desktop, Wireless Keyboard, Wireless Mouse, Power Adapter, User Manual",
            Model: "22-dd2456",
            "Model Name": "All-in-One",
            Color: "Jet black",
            Brand:"HP",
            Display: "21.5 inch",
            Resolution: "1920 x 1080 Pixel",
            OS: "Windows 11 Home",
            Processor: "Core i3",
            "Processor Model": "Core i3",
            Storage: "256 GB SSD + 1TB HDD",
            USB:"2 x SuperSpeed USB Type-A 5Gbps signaling rate, 2 x USB 2.0 Type-A",
            Bluetooth:"v4.2",
            HDMI:"1 x HDMI 1.4",
            RAM: "8GB of RAM",
            "Wi-Fi version": "Realtek RTL8821CE-M 802.11a/b/g/n/ac (1x1) Wi-Fi",
            Warranty: "1 Year Onsite Warranty HP Warranty and Free Transit Insurance"
        }
    },
    {
        _id: "044cb750-fbad-11ed-be56-0242ac120002",
        title: "HP All-in-One Core i5 (8 GB DDR4/512 GB SSD/Windows 11 Home/Intel UHD Graphics/23.8 Inch Screen/24-cb1901in)  (Starry white, 525 mm x 641 mm x 277 mm, 5.37 kg)",
        seller: "MTAILMODEECOM",
        price: "60,800",
        offerPrice: "60,800",
        discount: "0% off",
        category: "computers",
        image: "https://t.ly/qMPZ",
        rating: "4",
        features:
        {
            "In Box": "All in One Desktop, HP 710 White Wireless Keyboard and Mouse Combo, Power Adapter, User Manual",
            Model: "24-cb1901in",
            "Model Name": "All-in-One",
            Color: "Starry white",
            Brand:"HP",
            Display: "23.8 Inch",
            Resolution: "1920 x 1080 Pixel",
            OS: "Windows 11 Home",
            Processor: "Core i5",
            "Processor Model": "Core i5",
            Storage: "512 GB SSD",
            USB:"1 x SuperSpeed USB Type-A 5 Gbps Signaling Rate, 1 x SuperSpeed USB Type-A 5 Gbps Signaling Rate, 2 x USB 2.0 Type-A",
            Bluetooth:"v4.2",
            HDMI:"1 x HDMI 1.4",
            RAM: "8GB DDR4",
            "Wi-Fi version": "Realtek RTL8821CE-M 802.11a/b/g/n/ac (1x1) Wi-Fi",
            Warranty: "1 Year Onsite Warranty HP Warranty and Free Transit Insurance."
        }
    },
    {
        _id: "9ad1e9fc-fbad-11ed-be56-0242ac120002",
        title: "HP All-in-One Ryzen 3 Dual Core (4 GB DDR4/512 GB SSD/Windows 11 Home/AMD Radeon Graphics/21.5 Inch Screen/22-dd0786in) with MS Office  (Snow white, 380.7 mm x 490.3 mm x 204.5 mm, 5.7 kg)",
        seller: "MTAILMODEECOM",
        price: "47,266",
        offerPrice: "42,990",
        discount: "9% off",
        category: "computers",
        image: "https://t.ly/qMPZ",
        rating: "4",
        features:
        {
            "In Box": "All in One Desktop, HP 125 USB White Wired Keyboard, HP Wired White Mouse, Power Adapter, User Manual",
            Model: "22-dd0786in",
            "Model Name": "All-in-One",
            Color: "Snow white",
            Brand:"HP",
            Display: "21.5 inch",
            Resolution: "1920 x 1080 Pixel",
            OS: "Windows 11 Home",
            Processor: "Ryzen 3 Dual Core",
            "Processor Model": "Ryzen 3",
            Storage: "512 GB SSD",
            USB:"2 x SuperSpeed USB Type-A 5 Gbps Signaling Rate, 2 x USB 2.0 Type-A",
            Bluetooth:"v4.2",
            RAM: "4GB DDR4",
            Utility:"Microsoft Office Home & Student Edition 2021",
            "Wi-Fi version": "Realtek RTL8821CE 802.11a/b/g/n/ac (1x1) Wi-Fi",
            Warranty: "1 Year Onsite Warranty HP Warranty and Free Transit Insurance"
        }
    },
    {
        _id: "246b190e-fbae-11ed-be56-0242ac120002",
        title: "ASUS Vivo AiO V241 Core i3 (8 GB DDR4/256 GB SSD/Windows 11 Home/23.8 Inch Screen/V241EAK-WA018WS) with MS Office  (White, 409 mm x 540 mm x 165 mm, 5.4 kg)",
        seller: "MTAILMODEECOM",
        price: "61,990",
        offerPrice: "45,990",
        discount: "25% off",
        category: "computers",
        image: "https://t.ly/qS_L",
        rating: "4.2",
        features:
        {
            "In Box": "All-in-One Desktop, Wireless Keyboard, Wireless Mouse, Power Adapter, User Manual",
            Model: "V241EAK-WA018WS",
            "Model Name": "Vivo AiO V241",
            Color: "White",
            Brand:"ASUS",
            Display: "23.8 Inch",
            Resolution: "1920 x 1080 Pixel",
            OS: "Windows 11 Home",
            Processor: "Core i3",
            "Processor Model": "intel Core i3 1115G4",
            Storage: "256 GB SSD",
            USB:"1 x USB 2.0 Type-A, 4 x USB 3.2 Gen 1 Type-A",
            Bluetooth:"v5.0",
            HDMI:"1 x HDMI 1.4",
            RAM: "8GB DDR4",
            Warranty: "1 Year Onsite Warranty ASUS Warranty and Free Transit Insurance."
        }
    },
    {
        _id: "bcd95322-fbae-11ed-be56-0242ac120002",
        title: "ASUS AiO A3 Series Touch Panel Core i5 (8 GB DDR4/512 GB SSD/Windows 11 Home/23.8 Inch Screen/A3402WBAT-WA001WS) with MS Office  (White, 423 mm x 539 mm x 165 mm, 5.4 Kg)",
        seller: "MTAILMODEECOM",
        price: "83,990",
        offerPrice: "67,990",
        discount: "19% off",
        category: "computers",
        image: "https://t.ly/Nqxd",
        rating: "4.2",
        features:
        {
            "In Box": "All-in-One Desktop, Wireless Keyboard, Wireless Mouse, Power Adapter, User Manual",
            Model: "A3402WBAT-WA001WS",
            "Model Name": "AiO A3 Series Touch Panel",
            Color: "White",
            Brand:"ASUS",
            Display: "23.8 Inch",
            Resolution: "1920 x 1080 Pixel",
            OS: "Windows 11 Home",
            Processor: "Core i5",
            "Processor Model": "Core i5-1235U",
            Storage: "512 GB SSD",
            USB:"2 x USB 2.0 Type-A, 1 x USB 3.2 Gen 1 Type-C, 3 x USB 3.2 Gen 1 Type-A",
            Bluetooth:"v5.2",
            HDMI:"1x HDMI in 1.4, 1x HDMI out 1.4",
            RAM: "8GB DDR4",
            Utility:"Office Home and Student 2021",
            Warranty: "1 Year Onsite Warranty ASUS Warranty and Free Transit Insurance."
        }
    },
    {
        _id: "555c5eeec-fbaf-11ed-be56-0242ac120002",
        title: "ASUS Vivo AiO V241 Core i5 (8 GB DDR4/512 GB SSD/Windows 11 Home/23.8 Inch Screen/V241EAK-WA020WS) with MS Office  (White, 409 mm x 540 mm x 165 mm, 5.4 kg)",
        seller: "MTAILMODEECOM",
        price: "77,990",
        offerPrice: "53,990",
        discount: "30% off",
        category: "computers",
        image: "https://t.ly/wf3s",
        rating: "4.9",
        features:
        {
            "In Box": "All-in-One Desktop, Wireless Keyboard, Wireless Mouse, Power Adapter, User Manual",
            Model: "V241EAK-WA020WS",
            "Model Name": "Vivo AiO V241",
            Color: "White",
            Brand:"ASUS",
            Display: "23.8 Inch",
            Resolution: "1920 x 1080 Pixel",
            OS: "Windows 11 Home",
            Processor: "Core i5",
            "Processor Model": "Intel Core i5 1135G7",
            Storage: "512 GB SSD",
            USB:"1 x USB 2.0 Type-A, 4 x USB 3.2 Gen 1 Type-A",
            Bluetooth:"v5.0",
            HDMI:"1 x HDMI 1.4",
            RAM: "8GB DDR4",
            Warranty: "1 Year Onsite Warranty ASUS Warranty and Free Transit Insurance."
        }
    },
    {
        _id: "07edb18e-fbdf-11ed-be56-0242ac120002",
        title: "APPLE All-in-One Core i5 (6th Gen) (8 GB DDR3/2 TB/Mac OS X Lion/2 GB/27 Inch Screen/MK482HN/A)  (Silver)",
        seller: "OmniTechRetail",
        price: "1,88,900",
        offerPrice: "1,62,490",
        discount: "13% off",
        category: "computers",
        image: "https://t.ly/iq46",
        rating: "4.9",
        features:
        {
            "In Box": "AIO Computer, HP USB Wired Keyboard, HP USB Wired Optical Mouse",
            Model: "MK482HN/A",
            "Model Name": "All-in-One",
            Color: "Silver",
            Brand:"Apple",
            Display: "27 inch",
            Resolution: "1920 x 1080 Pixel",
            OS: "Mac OS X Lion",
            Processor: "Core i5 (6th Gen)",
            "Processor Model": "Intel Core i5 Quad‑core",
            Storage: "2TB HDD",
            "Dedicated Graphic Memory":"2GB",
            USB:"USB2.0 , USB3.0",
            RAM: "8 GB DDR3",
            Warranty: "1 Year manufacturer warranty"
        }
    },
    {
        _id: "e14a3ce0-fbdf-11ed-be56-0242ac120002",
        title: "Lenovo ideacentre Core i3 (10th Gen) (8 GB DDR4/512 GB SSD/Windows 10 Home/23.8 Inch Screen/A340-24IWL) with MS Office  (Black, 54.1 cm x 43.35 cm x 18.53 cm, 5.87 Kg)",
        seller: "DealAuthentic",
        price: "60,000",
        offerPrice: "56,400",
        discount: "6% off",
        category: "computers",
        image: "https://t.ly/_xUZ",
        rating: "4.6",
        features:
        {
            "In Box": "Laptop, Power Adaptor, User Guide, Warranty Documents",
            Model: "A340-24IWL",
            "Model Name": "ideacentre",
            Color: "Black",
            Brand:"Lenovo",
            Display: "23.8 inch",
            Resolution: "1920 x 1080 Pixel",
            OS: "Windows 10 Home",
            Processor: "Core i3 (10th Gen)",
            "Processor Model": "10110U",
            "Cache Memory":"4MB",
            "Integrated Graphic Processor":"Intel UHD Graphics",
            Storage: "512 GB SSD",
            USB:"Rear Ports: 2 x USB 2.0, 1 x USB 3.1 Gen 2 (USB 3.1 Gen 1 for Celeron and Pentium Models), Left Ports:1 x USB 3.1 Gen 2 (USB 3.1 Gen 1 for Celeron and Pentium Models)",
            Bluetooth:"v4.0",
            HDMI:"1 x HDMI 1.4",
            RAM: "8 GB DDR4",
            "Utility":"Microsoft Office Home and Student 2019",
            Warranty: "1 Year Onsite Warranty"
        }
    },
    {
        _id: "a87fcfd2-fbe0-11ed-be56-0242ac120002",
        title: "HP All-in-One Core i3 (8 GB DDR4/1 TB/256 GB SSD/Windows 11 Home/Intel UHD Graphics 730/23.8 Inch Screen/24-ck0550in)  (Jet black, 410.9 mm x 641 mm x 277 mm, 6.69 kg)",
        seller: "MTAILMODEECOM",
        price: "63,800",
        offerPrice: "56,990",
        discount: "10% off",
        category: "computers",
        image: "https://t.ly/v5Xzi",
        rating: "3.8",
        features:
        {
            "In Box": "All in One Desktop, HP 710 Black Wireless Keyboard and Mouse Combo, Power Adapter, User Manual",
            Model: "24-ck0550in",
            "Model Name": "All-in-One",
            Color: "JetBlack",
            Brand:"HP",
            Display: "23.8 inch",
            Resolution: "1920 x 1080 Pixel",
            OS: "Windows 11 Home",
            Processor: "Core i3",
            "Processor Model": "Core i3",
            "Cache Memory":"12 MB",
            "Integrated Graphic Processor":"Intel UHD Graphics 730",
            Storage: "256GB SSD + 1TB HDD",
            USB:"1 x SuperSpeed USB Type-A 5 Gbps Signaling Rate, 2 x USB 2.0 Type-A, 1 x SuperSpeed USB Type-A 5 Gbps Signaling Rate",
            Bluetooth:"v4.2",
            HDMI:"1 x HDMI 1.4",
            RAM: "8 GB DDR4",
            Warranty: "1 Year Onsite Warranty HP Warranty and Free Transit Insurance"
        }
    },
    {
        _id: "6cf2e66a-fbe1-11ed-be56-0242ac120002",
        title: "HP All-in-One Core i3 (8 GB DDR4/Windows 11 Home/23.8 Inch Screen/24-cb1802in)  (Jet black)",
        seller: "MTAILMODEECOM",
        price: "58,174",
        offerPrice: "52,990",
        discount: "8% off",
        category: "computers",
        image: "https://t.ly/9y2m",
        rating: "3.4",
        features:
        {
            "In Box": "All-in-One Desktop, Wireless Keyboard, Wireless Mouse, Power Adapter, User Manual",
            Model: "24-cb1802in",
            "Model Name": "All-in-One",
            Color: "Jet Black",
            Brand:"HP",
            Display: "23.8 inch",
            Resolution: "1920 x 1080 Pixel",
            OS: "Windows 11 Home",
            Processor: "Core i3",
            "Processor Model": "Core i3",
            Storage: "256GB SSD + 1TB HDD",
            USB:"2 x USB Type-A 5Gbps signaling rate, 2 x USB 2.0 Type-A",
            RAM: "8 GB DDR4",
            Warranty: "1 Year Onsite Warranty"
        }
    },
    {
        _id: "05bc66c8-fbe2-11ed-be56-0242ac120002",
        title: "HP All-in-One 27 Core i3 (8 GB DDR4/512 GB SSD/Windows 11 Home/27 Inch Screen/All-in-One 27-CB1345IN) with MS Office  (Starry white)",
        seller: "TheBrandPartner",
        price: "61,250",
        offerPrice: "57,990",
        discount: "5% off",
        category: "computers",
        image: "https://t.ly/WyH4",
        rating: "3.4",
        features:
        {
            "In Box": "Desktop, Keyboard, Mouse",
            Model: "All-in-One 27-CB1345IN",
            "Model Name": "All-in-One 27",
            Color: "Starry white",
            Brand:"HP",
            Display: "23.8 inch",
            Resolution: "1920 x 1080 Pixel",
            OS: "Windows 11 Home",
            Processor: "Core i3",
            "Processor Model": "27-CB1345IN",
            "Cache Memory":"6 MB",
            Storage: "512GB SSD",
            USB:"3",
            Bluetooth:"yes",
            RAM: "8 GB DDR4",
            Warranty: "1 Year Manufacturer Warranty"
        }
    },
    {
        _id: "87ee5b92-fbe2-11ed-be56-0242ac120002",
        title: "APPLE 2021 iMac with 4.5K Retina display M1 (8 GB Unified/256 GB SSD/Mac OS Big Sur/24 Inch Screen/MGPH3HN/A)  (Green, 461 mm x 547 mm x 130 mm, 4.48 kg)",
        seller: "SuperComNet",
        price: "1,39,900",
        offerPrice: "1,19,990",
        discount: "14% off",
        category: "computers",
        image: "https://t.ly/Vip6",
        rating: "4.8",
        features:
        {
            "In Box": "iMac, Magic Keyboard with Touch ID, Magic Mouse, Power Adapter (143W), Power Cord (2 m), USB-C to Lightning Cable",
            Model: "MGPH3HN/A",
            "Model Name": "2021 iMac with 4.5K Retina display",
            Color: "Green",
            Brand:"Apple",
            Display: "24 inch",
            Resolution: "4480 x 2520 Pixels",
            OS: "Mac OS Big Sur",
            Processor: "M1",
            "Processor Model": "NA",
            "Cache Memory":"6 MB",
            USB:"2 x Thunderbolt / USB 4 Ports, 2 x USB 3 Ports (upto 10 GBPS",
            Bluetooth:"v5.0",
            RAM: "8 GB Unified",
            Utility:"Built-in Apps: App Store, Books, Calendar, Contacts, FaceTime, Find My, GarageBand, Home, Mail, Messages, Music, Notes, Numbers, Pages, Photo Booth, Photos, Podcasts, Preview, QuickTime Player, Reminders, Safari, Siri, Stocks, Time Machine, TV, Keynote, Maps, Voice Memos, iMovie",
            "Other Features":"8-core CPU with 4 Performance Cores and 4 Efficiency Cores, 8-core GPU, 16-core Neural Engine, 1080p FaceTime HD Camera with M1 Image Signal Processor",
            Warranty: "1 Year Manufacturer Warranty"
        }
    },
    {
        _id: "37036e60-fbe3-11ed-be56-0242ac120002",
        title: "APPLE 2021 iMac with 4.5K Retina display M1 (8 GB Unified/512 GB SSD/Mac OS Big Sur/24 Inch Screen/MGPD3HN/A)  (Silver, 461 mm x 547 mm x 130 mm, 4.48 kg)",
        seller: "TREASURE HAUL ONLINE",
        price: "1,59,900",
        offerPrice: "1,59,900",
        discount: "0% off",
        category: "computers",
        image: "https://t.ly/RH08T",
        rating: "4.5",
        features:
        {
            "In Box": "iMac, Magic Keyboard with Touch ID, Magic Mouse, Power Adapter (143W), Power Cord (2 m), USB-C to Lightning Cable",
            Model: "MGPD3HN/A",
            "Model Name": "2021 iMac with 4.5K Retina display",
            Color: "Silver",
            Brand:"Apple",
            Display: "24 inch",
            Resolution: "4480 x 2520 Pixels",
            OS: "Mac OS Big Sur",
            Processor: "M1",
            "Processor Model": "NA",
            Storage: "512GB SSD",
            USB:"2 x Thunderbolt / USB 4 Ports, 2 x USB 3 Ports (upto 10 GBPS)",
            Bluetooth:"v5.0",
            RAM: "8 GB Unified",
            Utility:"Built-in Apps: App Store, Books, Calendar, Contacts, FaceTime, Find My, GarageBand, Home, Mail, Messages, Music, Notes, Numbers, Pages, Photo Booth, Photos, Podcasts, Preview, QuickTime Player, Reminders, Safari, Siri, Stocks, Time Machine, TV, Keynote, Maps, Voice Memos, iMovie",
            "Other Features":"8-core CPU with 4 Performance Cores and 4 Efficiency Cores, 8-core GPU, 16-core Neural Engine, 1080p FaceTime HD Camera with M1 Image Signal Processor",
            Warranty: "1 Year Limited Warranty APPLE Warranty and Free Transit Insurance"
        }
    },
    {
        _id: "19d4f1e6-fbe4-11ed-be56-0242ac120002",
        title: "DELL Inspiron 7710 Core i7 (16 GB DDR4/1 TB/512 GB SSD/Windows 11 Home/27 Inch Screen/Inspiron 7710 All in One) with MS Office  (Pearl White with Triangle Stand, 41 cm x 60 cm x 20 cm, 7 kg)",
        seller: "TComputronicsMultivisio",
        price: "1,65,000",
        offerPrice: "1,59,000",
        discount: "3% off",
        category: "computers",
        image: "https://t.ly/2PRJ",
        rating: "2.8",
        features:
        {
            "In Box": "All In One, User Manual, Keyboard, Mouse",
            Model: "Inspiron 7710 All in One",
            "Model Name": "Inspiron 7710",
            Color: "Pearl White with Triangle Stand",
            Brand:"DELL",
            Display: "27 inch",
            Resolution: "1920 x 1080 Pixel",
            OS: "Windows 11 Home",
            Processor: "Core i7",
            "Processor Model": "Intel® Core i7-1255U",
            "Integrated Graphic Processor":"Intel® Iris® Xe Graphics",
            "Cache Memory":"12 MB",
            Storage: "512GB SSD + 1TB HDD",
            USB:"1 USB 3.1 Gen 1 port with Power on/Wake-up support, 2 USB 3.1 Gen 1 ports, 1 USB 3.1 Gen 2 port with PowerShare, 1 USB 3.2 Type-C Gen 2 port",
            Bluetooth:"Bluetooth 5.2",
            HDMI:"1 HDMI 1.4b port, 1 HDMI-in 1.4b port",
            RAM: "16 GB DDR4",
            Utility:"Office Home & Student 2021",
            "Other Features":"Processor :- 12 Gen Intel® Core™ i7-1255U (12 MB cache, 10 cores, 12 threads, up to 4.70 GHz Turbo) Operating System, Memory :- 16GB, 2x8GB, DDR4, 3200MHz, Hard Drive :- 512GB Solid State Drive (Boot) + 1TB 5400RPM Hard Drive (Storage), Display :- 27-inch FHD (1920 x 1080) Narrow Border Infinity Touch Display with Wide Viewing Angle, Operating System :- Windows 11 Home Single Language, English, Microsoft Office :- Office Home & Student 2021, Video Card :- Intel® Iris® Xe Graphics, Keyboard :- Dell Pro Wireless Keyboard and Mouse US English - KM5221W - White, Colour :- Pearl White with Triangle Stand",
            Warranty: "3 Year Manufacturing Warranty"
        }
    },
    {
        _id: "14e54614-fc5b-11ed-be56-0242ac120002",
        title: "ZEBRONICS ZEB-USB150WF1 WiFi Mini USB Adapter  (Black)",
        seller: "indiaflashmartstore",
        price: "499",
        offerPrice: "328",
        discount: "34% off",
        category: "networking",
        image: "https://t.ly/K43y",
        rating: "3.9",
        features:
        {
            "In Box": "1 unit",
             "Model Name": "ZEB-USB150WF1 WiFi Mini",
            Warranty: "1 Year"
        }
    },
    {
        _id: "87280388-fc5b-11ed-be56-0242ac120002",
        title: "TP-Link TL-WN725N Wi-Fi Receiver 150 Mbps Wireless Nano USB Adapter  (Black)",
        seller: "RetailNet",
        price: "999",
        offerPrice: "499",
        discount: "50% off",
        category: "networking",
        image: "https://t.ly/W0se",
        rating: "4.4",
        features:
        {
            "In Box": "150 Mbps Wireless N Nano USB Adapter, Resource CD, Quick Installation Guide",
            "OS Supported":"Windows 10/8.1/8/7/XP, Mac OS X, Linux",
            Warranty: "3 Years Limited Carry In Warranty"
        }
    },
    {
        _id: "ec15e512-fc5b-11ed-be56-0242ac120002",
        title: "TP-link Archer T2U Plus AC600 High Gain Wireless Dual Band USB Adapter  (Black)",
        seller: "RetailNet",
        price: "2,199",
        offerPrice: "1,199",
        discount: "45% off",
        category: "networking",
        image: "https://t.ly/nMsy",
        rating: "4.4",
        features:
        {
            "In Box": "1 Wireless Dual Band USB Adapter, Quick Installation Guide, Resource CD",
            "OS Supported":"Windows XP, Windows 7, Windows 8, Windows 8.1, Windows 10, Mac OS X 10.9 - 10.14",
            Warranty: "3 Years Limited Carry In Warranty"
        }
    },
    {
        _id: "3b8f2d42-fc5c-11ed-be56-0242ac120002",
        title: "Tobo TD-CSR 4.0 Mini Bluetooth USB Adapter  (Black)",
        seller: "Tobo",
        price: "999",
        offerPrice: "284",
        discount: "71% off",
        category: "networking",
        image: "https://t.ly/jbZx",
        rating: "3.7",
        features:
        {
            "In Box": "BOX",
            "Model Name":"TD-CSR 4.0 Mini Bluetooth",
            Warranty: "1 Months Manufacturer Warranty"
        }
    },
    {
        _id: "9ca31f4e-fc5c-11ed-be56-0242ac120002",
        title: "TP-Link TL-WN823N 300Mbps Mini Wireless N USB Adapter  (Black)",
        seller: "Tobo",
        price: "1,358",
        offerPrice: "599",
        discount: "55% off",
        category: "networking",
        image: "https://t.ly/S5Ld",
        rating: "4.3",
        features:
        {
            "In Box": "BOX",
            "Model Name":"Wireless Adapter, Resource CD, Quick Installation Guide",
            "OS Supported":"Windows 8.1/8/7/XP, Mac OS, Linux",
            Warranty: "3 Years Limited Carry In Warranty"
        }
    },
    {
        _id: "fd57c448-fc5c-11ed-be56-0242ac120002",
        title: "Mi Router 4A Gigabit Edition 1200 Mbps Router  (White, Dual Band)",
        seller: "MTAILMODEECOM",
        price: "2,999",
        offerPrice: "1,299",
        discount: "56% off",
        category: "networking",
        image: "https://t.ly/sv96O",
        rating: "4.1",
        features:
        {
            "In Box": "1 Router, User Manual, Power Cable",
            "Model Name":"DVB4272IN",
            Brand:"MI",
            Color:"White",
            "Wireless Speed":"1200 Mbps",
            Warranty: "1 Year Warranty"
        }
    },
    {
        _id: "76aff414-fc5d-11ed-be56-0242ac120002",
        title: "TP-Link Archer C6 MU-MIMO Gigabit 1200 Mbps Wireless Router  (Black, Dual Band)",
        seller: "RetailNet",
        price: "4,999",
        offerPrice: "2,599",
        discount: "48% off",
        category: "networking",
        image: "https://t.ly/K0ps",
        rating: "4.4",
        features:
        {
            "In Box": "1 Router, Power Adapter, RJ-45 Ethernet Cable, Quick Installation Guide",
            "Model Name":"Archer C6 MU-MIMO Gigabit",
            Brand:"TP-Link",
            Color:"Black",
            "Wireless Speed":"1200 Mbps",
            Warranty: "3 Year Warranty"
        }
    },
    {
        _id: "c94f3a18-fc5d-11ed-be56-0242ac120002",
        title: "TP-Link Archer C20 AC WiFi 750 MBPS Wireless Router  (Blue, Dual Band)",
        seller: "RetailNet",
        price: "2,399",
        offerPrice: "1,599",
        discount: "33% off",
        category: "networking",
        image: "https://t.ly/-xJa",
        rating: "4.3",
        features:
        {
            "In Box": "Wi-Fi Router Archer C20, Power Adapter, RJ45 Ethernet Cable, Quick Installation Guide",
            "Model Name":"Archer C20 AC WiFi",
            Brand:"TP-Link",
            Color:"Blue",
            "Wireless Speed":"750 Mbps",
            Warranty: "3 Years TP-LINK India Warranty"
        }
    },
    {
        _id: "35d5f9c4-fc5e-11ed-be56-0242ac120002",
        title: "TP-Link archer mr200 (EU) 750 Mbps 4G Router  (Black, Dual Band)",
        seller: "RetailNet",
        price: "10,749",
        offerPrice: "5,199",
        discount: "51% off",
        category: "networking",
        image: "https://t.ly/wcLYe",
        rating: "3.9",
        features:
        {
            "In Box": "AC750 Wireless Dual Band 4G LTE Router Archer MR200, RJ45 Ethernet Cable, Power Adapter, Quick Installation Guide",
            "Model Name":"archer mr200 (EU)",
            Brand:"TP-Link",
            Color:"Black",
            "Wireless Speed":"750 Mbps",
            Warranty: "3 Years TP-LINK India Warranty"
        }
    },
    {
        _id: "9adea7f8-fc5e-11ed-be56-0242ac120002",
        title: "TP-Link RE200 750 Mbps WiFi Range Extender  (White, Dual Band)",
        seller: "RetailNet",
        price: "4,245",
        offerPrice: "8,893",
        discount: "55% off",
        category: "networking",
        image: "https://t.ly/meuVp",
        rating: "4.3",
        features:
        {
            "In Box": "AC750 WiFi Range Extender RE200,RJ-45 Ethernet Cable,Resource CD,Quick Installation Guide",
            "Model Name":"RE200",
            Brand:"TP-Link",
            Color:"White",
            "Wireless Speed":"750 Mbps",
            Warranty: "3 Years TP-LINK India Warranty"
        }
    },
    {
        _id: "07909960-fc5f-11ed-be56-0242ac120002",
        title: "UNIY UY310 4G WiFi USB Hotspot LTE Dongle Support All sim network 2G/3G/4G 150Mbps Data Card  (White)",
        seller: "iGRAB",
        price: "2,500",
        offerPrice: "1,881",
        discount: "24% off",
        category: "networking",
        image: "https://t.ly/H4FC",
        rating: "4.2",
        features:
        {
            "In Box": "1x UNIY UY (310) HOTSPOT",
            "Model Name":"UY310 4G WiFi USB Hotspot LTE Dongle Support All sim network 2G/3G/4G 150Mbp",
            "Expandable Memory Capacity":"128 GB",
            Brand:"UNIY",
            Color:"White",
            "Wireless Speed":"750 Mbps",
            Warranty: "1 Year"
        }
    },
    {
        _id: "72273e8c-fc5f-11ed-be56-0242ac120002",
        title: "Melbon 4G LTE WiFi Dongle with All SIM 4G,5G Network Support, Plug & Play Sim Insert Data Card  (Black)",
        seller: "BellstarTradingPvtLtd",
        price: "4,999",
        offerPrice: "1,699",
        discount: "66% off",
        category: "networking",
        image: "https://t.ly/MGPu",
        rating: "3.9",
        features:
        {
            "In Box": "1",
            "Model Name":"4G LTE WiFi Dongle with All SIM 4G,5G Network Support, Plug & Play Sim Insert",
            "Expandable Memory Capacity":"4 GB",
            Brand:"Melbon",
            Color:"Black",
            "Wireless Speed":"750 Mbps",
            Warranty: "6 Months"
        }
    },
    {
        _id: "e636df4e-fc5f-11ed-be56-0242ac120002",
        title: "Nexta Mobile Battery For Jio WiFi Dongle M2S JioFi 2 Wireless Router/ Jio Fi2 4G / M2 Data Card  (Black)",
        seller: "OriginallProduct",
        price: "899",
        offerPrice: "445",
        discount: "50% off",
        category: "networking",
        image: "https://t.ly/cs_w",
        rating: "3.7",
        features:
        {
            "In Box": "Jio m2s data card battery",
            "Model Name":"Mobile Battery For Jio WiFi Dongle M2S JioFi 2 Wireless Router/ Jio Fi2 4G / M2",
            "Expandable Memory Capacity":"32 GB",
            Brand:"Nexta",
            Color:"Black",
            "Wireless Speed":"300 Mbps",
            Warranty: "7 Days"
        }
    },
    {
        _id: "619a9572-fc60-11ed-be56-0242ac120002",
        title: "Nexta Reliance Wi-Pod WD670 4G LTE Dongle All Sim Supported 4G Router Data Card  (Black)",
        seller: "Deltamart1",
        price: "5,999",
        offerPrice: "1,939",
        discount: "67% off",
        category: "networking",
        image: "https://t.ly/IPBZ",
        rating: "3.4",
        features:
        {
            "In Box": "Wifi data card, usb cable, battery",
            "Model Name":"Reliance Wi-Pod WD670 4G LTE Dongle All Sim Supported 4G Router",
            "Expandable Memory Capacity":"64 GB",
            Brand:"Nexta",
            Color:"Black",
            "Wireless Speed":"300 Mbps",
            Warranty: "1 Year"
        }
    },
    {
        _id: "52b74f36-fc61-11ed-be56-0242ac120002",
        title: "X88 Pro 4G LTE Wireless WiFi Modem USB Dongal with All Sim Network Support 150 mbps Data Card  (Black)",
        seller: "Deltamart1",
        price: "2,999",
        offerPrice: "1,695",
        discount: "43% off",
        category: "networking",
        image: "https://t.ly/ZwXC",
        rating: "4",
        features:
        {
            "In Box": "1 USB Data Card, 1 User Manual",
            "Model Name":"4G LTE Wireless WiFi Modem USB Dongal with All Sim Network Support 150 mbps",
            "Expandable Memory Capacity":"32 GB",
            Brand:"Nexta",
            Color:"Black",
            "Wireless Speed":"150 Mbps",
            Warranty: "3 Months Warranty"
        }
    },
    {
      _id: "d9067bf1-3f72-4169-9440-56525d611c55",
      title: "McAfee 1 PC 3 Years Anti-virus (Email Delivery - No CD)  (Standard Edition)",
      seller: "ArhamWorld",
      price: "699",
      offerPrice: "640",
      discount: "8% off",
      category: "software",
      image: "https://t.ly/WRarA",
      rating: "4.4",
      features:
      {
          "In Box": "License Key",
          "Type":"Anti-virus",
          Brand:"McAfee",
          "Download Size":"350 MB",
          "Subscription Validity":"3 Years",
          Processor:"1 GHz Processor, Internet Connection (High-speed Connection Recommended)",
          "Operating System Version":"Microsoft Windows 11, 10, 8.1 fully patched (32- and 64-bit)",
      }
  },
  {
      _id: "041192b7-a54d-493e-88f4-1d9ade70fff2",
      title: "QUICK HEAL 1 PC PC 1 Year Anti-virus (Email Delivery - No CD)  (Home Edition)",
      seller: "InfoWise",
      price: "979",
      offerPrice: "449",
      discount: "54% off",
      category: "software",
      image: "https://t.ly/3hSO",
      rating: "4.3",
      features:
      {
          "In Box": "Quick Heal Key 1 PC 1 Year Activation Code",
          "Type":"Anti-virus",
          Brand:"QUICK HEAL",
          "Download Size":"1 MB",
          "Subscription Validity":"3 Years",
          Processor:"1 GHz or Above",
          "Operating System Version":"Windows 7, Windows 8, Windows 8.1, Windows 10",
      }
  },
  {
      _id: "ac8366fe-80b2-4a41-8d7e-306c61737e89",
      title: "PremiumAV 1 PC 1 Year Anti-virus (Email Delivery - No CD)  (Standard Edition)",
      seller: "ATEVON",
      price: "149",
      offerPrice: "11",
      discount: "92% off",
      category: "software",
      image: "https://t.ly/CK9Y",
      rating: "3.5",
      features:
      {
          "In Box": "1 ESD - Electronic Software Download",
          "Type":"Anti-virus",
          Brand:"PremiumAV",
          "Download Size":"146.14 MB",
          "Subscription Validity":"1 Year",
          Processor:"300 MHz Intel Pentium Processor 1 GHz Intel Pentium Processor",
          "Operating System Version":"Windows 11, Windows 10, Windows 8, Windows 7, Windows XP",
      }
  },
  {
      _id: "2f5f7369-a031-4053-bd92-0acea1df6e2f",
      title: "Kaspersky New Subscription 1 PC PC 1 Year Anti-virus (Email Delivery - No CD)  (Standard Edition)",
      seller: "ArhamWorld",
      price: "599",
      offerPrice: "225",
      discount: "62% off",
      category: "software",
      image: "https://t.ly/c21I",
      rating: "4.4",
      features:
      {
          "In Box": "1 Digital Security Software",
          "Type":"Anti-virus",
          Brand:"Kaspersky",
          "Download Size":"180 MB",
          "Subscription Validity":"1 Year",
          Processor:"1 GHz Processor or Faster",
          "Operating System Version":"Windows",
      }
  },
  {
      _id: "7e35f768-4117-4d49-9650-b68a00c6b4d6",
      title: "Norton 360 for Gamers 2021 + Total Security for 3 Devices PC 1 Year Anti-virus (Email Delivery - No CD)  (Standard Edition)",
      seller: "L777",
      price: "2,999",
      offerPrice: "1,899",
      discount: "36% off",
      category: "software",
      image: "https://tinyurl.com/243xc7dz",
      rating: "4.2",
      features:
      {
          "In Box": "1 Digital Security Software",
          "Type":"Anti-virus",
          Brand:"Norton",
          "Download Size":"300 MB",
          "Subscription Validity":"1 Year",
          Processor:"For Windows 10, Windows 8, Windows 7 - 1 GHz, For Mac OS X 10.10.x (Yosemite) or Later (Intel Core 2 Duo, Core i3, Core i5, Core i7, or Xeon Processor)",
          "Operating System Version":"Windows",
      }
  },
  {
      _id: "a107be0a-8204-41b9-a301-53b954069446",
      title: "MICROSOFT Windows 11 Pro 32/64 Bit (1 User/PC, Lifetime Validity)",
      seller: "ShopSure",
      price: "4,499",
      offerPrice: "1,999",
      discount: "55% off",
      category: "software",
      image: "https://tinyurl.com/2ya9ewed",
      rating: "4.8",
      features:
      {
          "In Box": "Product Key With Official Download Link",
          "Model Number":"Windows 11",
          Brand:"MICROSOFT",
          "Inbuilt Security Software":"Windows Defender",
          "Subscription Validity":"Lifetime",
          Processor:"2 Ghz",
          "Hard Drive":"20 GB",
      }
  },
  {
      _id: "f05f14a9-9dca-4f20-ac32-3b84ac2037da",
      title: "vgcs Microsoft Windows 10 Professional 32Bit/64Bit 1 PC Laptop/ User: 32 And 64 Bits Windows 10 32 Bit, 64 Bit",
      seller: "ShopSure",
      price: "16,999",
      offerPrice: "8,500",
      discount: "49% off",
      category: "software",
      image: "https://tinyurl.com/y5jkwnnh",
      rating: "4.4",
      features:
      {
          "In Box": "Product Key With Official Download Link",
          "Model Number":"Microsoft Windows 10 Professional 32Bit/64Bit 1 PC Laptop/ User: 32 And 64 Bits",
          Brand:"MICROSOFT"
      }
  },
  {
      _id: "7d0fec8a-8acd-41bb-be6f-358f6f205f70",
      title: "MICROSOFT Windows 10 HOME (1 PC/User, Lifetime Validity) Latest 64/32 bit",
      seller: "ShopSure",
      price: "4,499",
      offerPrice: "1,999",
      discount: "55% off",
      category: "software",
      image: "https://tinyurl.com/56aaze3m",
      rating: "3.8",
      features:
      {
          "In Box": "Installation Guide & License Key",
          "Model Number":"Windows 10 HOME (1 PC/User, Lifetime Validity)",
          Brand:"MICROSOFT",
          "Inbuilt Security Software":"Windows Defender",
          "Subscription Validity":"Lifetime",
          Processor:"intel i3, intel i5, intel i7",
          "Hard Drive":"16 GB",
      }
  },
  {
      _id: "1f590013-f5b5-4b95-87b3-32ebabfe2578",
      title: "TekyMeky Kali Linux 2022.3 XFCE 32 Bit and 64 Bit Live Bootable 32 GB USB Pen Drive 64 Bit 64 Bit",
      seller: "Cosmos Sellers",
      price: "1,499",
      offerPrice: "999",
      discount: "33% off",
      category: "software",
      image: "https://tinyurl.com/yybhkx6w",
      rating: "3.2",
      features:
      {
          "In Box": "1",
          "Model Number":"Kali Linux 2022.3 XFCE 32 Bit and 64 Bit Live Bootable 32 GB USB Pen Drive",
      }
  },
  {
      _id: "3872a4e8-f1c3-4137-8596-dd8af81ae2bf",
      title: "ubuntu 16.04 Xenial Xerus DVD 32 bit & 64 bit",
      seller: "TechGuy4u",
      price: "599",
      offerPrice: "379",
      discount: "36% off",
      category: "software",
      image: "https://tinyurl.com/ypm6cn5e",
      rating: "2.8",
      features:
      {
          "In Box": "Ubuntu 16.04 DVD 32 & 64 bit",
          "Model Number":"16.04 Xenial Xerus",
          Brand:"Ubuntu",
          "Other Requirements":"1 GB RAMLifetime",
          Processor:"1 GHz or faster",
          "Hard Drive":"5 GB",
      }
  },
  {
      _id: "59cfa816-4cf4-44ed-8a94-0a7c1d9e176d",
      title: "MICROSOFT Office 365 Professional Plus For 5 Users/PC (Lifetime Validity)",
      seller: "ShopSure",
      price: "5,200",
      offerPrice: "2,449",
      discount: "5% off",
      category: "software",
      image: "https://tinyurl.com/52mbfxxp",
      rating: "5",
      features:
      {
          "In Box": "Installation Manual, Email + Password (Account)",
          Edition:"365 Professional Plus",
          "Model Number":"Office 365 Professional Plus For 5 Users/PC (Lifetime Validity)",
          Licenses:"5",
          Brand:"MICROSOFT",
          "Operating System":"MacOS, Windows"
      }
  },
  {
      _id: "c4d66160-6cae-42bc-904d-cfc8aa85ba17",
      title: "MICROSOFT Office Home & Student 2021 Email delivery in24 hours Lifetime Validity  (Lifetime)",
      seller: "ShopSure",
      price: "9,499",
      offerPrice: "6,749",
      discount: "28% off",
      category: "software",
      image: "https://tinyurl.com/48pk7a8c",
      rating: "3.5",
      features:
      {
          "In Box": "License Key",
          Edition:"365 Professional Plus",
          "Model Number":"Home & Student 2021",
          "Download Size":"1GB",
          Licenses:"1",
          Brand:"MICROSOFT",
          "Operating System":"MacOS, Windows",
          "RAM":"1GB",
          "Hard Disk Space":"500"
      }
  },
  {
      _id: "1e63e0e9-e11e-4b63-8afe-4bdf5b250119",
      title: "MICROSOFT Office Mac Home Business  (Lifetime)",
      seller: "ShopSure",
      price: "15,499",
      offerPrice: "7,400",
      discount: "52% off",
      category: "software",
      image: "https://tinyurl.com/yswc4sfd",
      rating: "4.3",
      features:
      {
          "In Box": "1 License Key",
          Type:"Activation Box",
          Edition:"Professional",
          "Model Number":"Home & Student 2021",
          Licenses:"1",
          Brand:"MICROSOFT",
          "Operating System":"MacOS",
          "RAM":"1GB",
      }
  },
  {
      _id: "a11edb30-93b9-47d8-9fec-9865e206f712",
      title: "COMPATIBLE Office Suite 2019 Edition CD DVD 100% compatibles with Microsoft Word and Excel for Windows 10-8-7-Vista-XP  (life time Year)",
      seller: "Cosmos Sellers",
      price: "599",
      offerPrice: "299",
      discount: "50% off",
      category: "software",
      image: "https://tinyurl.com/2p9sprdx",
      rating: "3.5",
      features:
      {
          "In Box": "1",
          Edition:"The large Office Suite program for word processing, spreadsheet analysis and presentations",
          Type:"Office Suite 2019",
          "Model Number":"Home & Student 2021",
          "Media Format":"DVD",
          Licenses:"1",
          Brand:"Open Office",
          "Operating System":"Windows 10 8 7, Vista, XP",
      }
  },
  {
      _id: "0b51b11b-a572-46cc-b42e-aae1b2441a2d",
      title: "wincial MS Office 365 Professional Lifetime Validity for PC MAC IOS & Android",
      seller: "EshopsIndia",
      price: "1,999",
      offerPrice: "558",
      discount: "72% off",
      category: "software",
      image: "https://tinyurl.com/cdynxumh",
      rating: "4.1",
      features:
      {
          "In Box": "Activation credentials and instructions",
          Type:"Activation Box",
          Edition:"Professional",
          "Model Number":"MS Office 365 Professional Lifetime Validity for PC MAC IOS & Android",
          Licenses:"1",
          Brand:"MICROSOFT",
      }
  },
  ]
